### ISSUE TITLE
A question about the exact size of the corpus

### ISSUE THREAD

**Issue by hamotahari** [persiannlp/persian-raw-text#1]
Hi,
Would you tell me what is the exact size of the corpus.
I have tried some times to download and now I am not sure if the downloaded file is a complete one or not.
My file (all corpus) shows 74991354317 bytes as its size. Is it correct?

PS: Maybe it is a good idea if there were e.g. sha1 digests of files.
PS2: Another point, it may be better if the files had provided as compressed.

Thanks
Hamzeh

**Comment by danyaljj** [comment]
Hamzeh, 
The best way to download these large files is via `gsutil`; this should give you the details information on the progress of your downloads: 
```
$ gsutil -m cp -R gs://danielk-files/farsi-text/merged_files/all_text_merged_cleaned.txt  .
Copying gs://danielk-files/farsi-text/merged_files/all_text_merged_cleaned.txt...
/ [0/1 files][600.2 MiB/ 69.8 GiB]   0% Done    
```
Does that resolve your issue? 

PS. Zipfile & SHA1: thanks, will consider adding them.

**Comment by hamotahari** [comment]
Yes, somehow resolved, thanks.
Thanks for gsutil too:-)

> Hamzeh,
> The best way to download these large files is via `gsutil`; this should give you the details information on the progress of your downloads:
> 
> ```
> $ gsutil -m cp -R gs://danielk-files/farsi-text/merged_files/all_text_merged_cleaned.txt  .
> Copying gs://danielk-files/farsi-text/merged_files/all_text_merged_cleaned.txt...
> / [0/1 files][600.2 MiB/ 69.8 GiB]   0% Done    
> ```
> 
> Does that resolve your issue?
> 
> PS. Zipfile & SHA1: thanks, will consider adding them.
