### ISSUE TITLE
Info about text corpus

### ISSUE THREAD

**Issue by azarezade** [persiannlp/persian-raw-text#2]
Thanks for this great raw text corpora! I wonder if you could provide more info about presian commoncrawl data. How it is extracted from commoncrawl data, is there a way to search in crawled site indices (like http://index.commoncrawl.org). Is it for example extracted from all indices which has `"languages": "fas"` attribute in a specific period of years?

**Comment by danyaljj** [comment]
I used the following tool to crawl data from commoncrawl: 

https://github.com/sdadas/commoncrawl-downloader

You can specify the target language in its command line; e.g., `-languages pl,en`.
